// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineAppConfig({
    ui: {
      colors: {
        primary: 'green',
        secondary: 'blue',
        success: 'green',
        info: 'blue',
        warning: 'yellow',
        error: 'red',
        neutral: 'slate',
        red: 'red',
        orange: 'orange',
        amber: 'amber',
        yellow: 'yellow',
        lime: 'lime',
        green: 'green',
        emerald: 'emerald',
        teal: 'teal',
        cyan: 'cyan',
        sky: 'sky',
        blue: 'blue',
        indigo: 'indigo',
        violet: 'violet',
        purple: 'purple',
        fuchsia: 'fuchsia',
        pink: 'pink',
        rose: 'rose',
      },
    },
  })